### PR TITLE
Fix: Do not skip HSTORE for logical connector as unsupported datatypes in export data from target

### LINKED ISSUE #2202: Support hstore datatype for live migration with fall-forward/fallback workflows with logical connector
Jira Link: [DB-14917](https://yugabyte.atlassian.net/browse/DB-14917)

### PR DESCRIPTION
**Pull request by priyanshi-yb**
…

### Describe the changes in this pull request
Not skipping the `HSTORE` datatype column's data in export data from target case for fall-forward/fall-back case.
fixes #2202 

### Describe if there are any user-facing changes

With the logical connector during fall-forward/fallback workflow, data HSTORE datatype column will be exported. 

### How was this pull request tested?

Manually

### Does your PR have changes that can cause upgrade issues? 
| Component        | Breaking changes? |
| :----------------------------------------------: | :-----------: |
| MetaDB                                                    | No |
| Name registry json                                        | No |
| Data File Descriptor Json                                 | No |
| Export Snapshot Status Json                               | No |
| Import Data State                                         | No |
| Export Status Json                                        | No |
| Data .sql files of tables                                 | No |
| Export and import data queue                              |  No |
| Schema Dump                                               | No |
| AssessmentDB                                              | No |
| Sizing DB                                                 | No |
| Migration Assessment Report Json                          | No |
| Callhome Json                                             | No |
| YugabyteD Tables                                          |  No |
| TargetDB Metadata Tables                                  | No |

### CODE REVIEW

File: yb-voyager/src/srcdb/postgres.go [hunk 1]
```diff
@@ -60,7 +60,8 @@ func GetPGLiveMigrationUnsupportedDatatypes() []string {
 }
 
 func GetPGLiveMigrationWithFFOrFBUnsupportedDatatypes() []string {
-	unsupportedDataTypesForDbzmYBOnly, _ := lo.Difference(YugabyteUnsupportedDataTypesForDbzm, PostgresUnsupportedDataTypes)
+	//TODO: add connector specific handling
```
Comment (makalaaneesh) [inline yb-voyager/src/srcdb/postgres.go:63]: I don't think we can at this point? 
If i understand correctly, `GetPGLiveMigrationWithFFOrFBUnsupportedDatatypes` is called by assess-migration. At this point, we don't know which connector they are going to use, so we can't really make that call. Correct?

File: yb-voyager/src/srcdb/yugabytedb.go [hunk 2]
```diff
@@ -38,7 +38,13 @@ import (
 )
 
 // Apart from these we also skip UDT columns and error out for array of enums as unsupported tables.
-var YugabyteUnsupportedDataTypesForDbzm = []string{"BOX", "CIRCLE", "LINE", "LSEG", "PATH", "PG_LSN", "POINT", "POLYGON", "TSQUERY", "TSVECTOR", "TXID_SNAPSHOT", "GEOMETRY", "GEOGRAPHY", "RASTER", "HSTORE"}
+var YugabyteUnsupportedDataTypesForDbzm = []string{"BOX", "CIRCLE", "LINE", "LSEG", "PATH", "PG_LSN", "POINT", "POLYGON", "TSQUERY", "TSVECTOR", "TXID_SNAPSHOT", "GEOMETRY", "GEOGRAPHY", "RASTER"}
```
Comment (makalaaneesh) [inline yb-voyager/src/srcdb/yugabytedb.go:41]: declare separate variables: 
- `YugabyteUnsupportedDataTypesForDbzmGrpc`
- `YugabyteUnsupportedDataTypesForDbzmLogicalReplication` 

have a single function `GetYugabyteUnsupportedDatatypesDbzm(isGrpcConnector)`

File: yb-voyager/src/srcdb/yugabytedb.go [hunk 3]
```diff
@@ -638,6 +644,12 @@ func (yb *YugabyteDB) filterUnsupportedUserDefinedDatatypes(tableName sqlname.Na
 func (yb *YugabyteDB) GetColumnsWithSupportedTypes(tableList []sqlname.NameTuple, useDebezium bool, isStreamingEnabled bool) (*utils.StructMap[sqlname.NameTuple, []string], *utils.StructMap[sqlname.NameTuple, []string], error) {
 	supportedTableColumnsMap := utils.NewStructMap[sqlname.NameTuple, []string]()
 	unsupportedTableColumnsMap := utils.NewStructMap[sqlname.NameTuple, []string]()
+
+	if yb.source.IsYBGrpcConnector {
+		//ONLY in case of grpc connector add HSTORE
+		YugabyteUnsupportedDataTypesForDbzm = append(YugabyteUnsupportedDataTypesForDbzm, "HSTORE")
```
Comment (makalaaneesh) [inline yb-voyager/src/srcdb/yugabytedb.go:650]: Use `GetYugabyteUnsupportedDatatypesDbzm(isGrpcConnector)` here.

File: yb-voyager/src/srcdb/postgres.go (hunk 1 above)
Comment (priyanshi-yb) [reply yb-voyager/src/srcdb/postgres.go:63]: yeah

**Review by makalaaneesh — APPROVED** [review]
LGTM. 
Regarding a test case, pls ensure that this gets covered along with the other broader task for testing all data types.

**Comment by priyanshi-yb** [comment]
> Regarding a test case, pls ensure that this gets covered along with the other broader task for testing all data types.

We already have a test case for hstore but we need to enable it for logical but currently the datatypes test itself fails for logical so can't test it properly we can fix it later. cc: @shubham-yb
