### PR TITLE
Import Data Resume-ability bug fix #208 and start clean behaviour change #209

### LINKED ISSUE #208: Bug: Import Data Resume-ability ability issues in case of retry
There has been cases observed when on retry the `import data` command it is not resuming instead reporting that the import of table has been done.

Fixes have been identified as follows:
1. On retry, ensure to take care of the case when only `*.D` splits are available in `exportDir/metainfo/data` directory and table is still in the interrupted stage, so just need to identify that table as interrupted and continue code to generate new splits and then import them.
2. In some cases, it has been observed that `*.D` are retried so for that to fix just ensure split generation in `splitDataFiles()` function should take into account the already generated `*.D` splits and continue generation of new splits after those.

### PR DESCRIPTION
**Pull request by sanyamsinghal**
Fix/changes are done as mentioned in corresponding tickets #208 and #209.

Test Plan:
Tested by simulating a similar scenario where only *.D splits are present on disruption/exit of yb-voyager import data command and on retry it is generating the remaining splits and continue
Also confirmed that the already Done splits are not regenerated-and-retried(which was happening previously)
For startClean behaviour testing, i just tested  it in combination with --table-list flag, it works fine now as expected.

### CODE REVIEW

File: yb-voyager/cmd/importData.go [hunk 1]
```diff
@@ -375,8 +375,13 @@ func generateSmallerSplits(taskQueue chan *SplitFileImportTask) {
...
 		fmt.Printf("Truncating all tables: %v\n", allTables)
 		truncateTables(allTables)
-		log.Infof("cleaning the database and %s/metadata/data directory", exportDir)
-		utils.CleanDir(exportDir + "/metainfo/data")
+
+		for _, table := range allTables {
+			tableSplitsPatternStr := fmt.Sprintf("%s.%s", table, SPLIT_INFO_PATTERN)
+			filePattern := filepath.Join(exportDir, "metainfo/data", tableSplitsPatternStr)
+			utils.ClearMatchingFiles(filePattern)
+			log.Infof("clearing the generated splits for table %q matching %q pattern", table, filePattern)
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:383]: Move the log line above before line 382.

File: yb-voyager/cmd/importData.go [hunk 2]
```diff
@@ -532,32 +533,9 @@ func splitDataFiles(importTables []string, taskQueue chan *SplitFileImportTask)
...
-				splitNum, _ := strconv.ParseInt(match[1], 10, 64)
-				offsetEnd, _ := strconv.ParseInt(match[2], 10, 64)
-				numLines, _ := strconv.ParseInt(match[3], 10, 64)
-				offsetStart := offsetEnd - numLines
-				if splitNum == LAST_SPLIT_NUM {
-					fileFullySplit = true
-				}
-				if splitNum > largestCreatedSplitSoFar {
-					largestCreatedSplitSoFar = splitNum
+				if !doneSplitRegexp.MatchString(filepath) {
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:541]: Why not just check if the file-name ends with `.D`?

File: yb-voyager/cmd/importData.go [hunk 3]
```diff
@@ -760,19 +738,23 @@ func getTablesToImport() ([]string, []string, []string, error) {
...
+		lastSplitPattern := fmt.Sprintf("%s/%s.%s.[CPD]", metaInfoDataDir, t, LAST_SPLIT_PATTERN)
 
 		doneMatches, _ := filepath.Glob(donePattern)
 		interruptedMatches, _ := filepath.Glob(interruptedPattern)
 		createdMatches, _ := filepath.Glob(createdPattern)
+		lastSplitMatches, _ := filepath.Glob(lastSplitPattern)
 
-		//[Important] This function's return result is based on assumption that the rate of ingestion is slower than splitting
-		if len(createdMatches) == 0 && len(interruptedMatches) == 0 && len(doneMatches) > 0 {
+		// Not Vaild Now: [Important] This function's return result is based on assumption that the rate of ingestion is slower than splitting
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:753]: Drop this comment.

File: yb-voyager/cmd/importData.go [hunk 4]
```diff
@@ -760,19 +738,23 @@ func getTablesToImport() ([]string, []string, []string, error) {
 		donePattern := fmt.Sprintf("%s/%s.%s.D", metaInfoDataDir, t, SPLIT_INFO_PATTERN)
 		interruptedPattern := fmt.Sprintf("%s/%s.%s.P", metaInfoDataDir, t, SPLIT_INFO_PATTERN)
 		createdPattern := fmt.Sprintf("%s/%s.%s.C", metaInfoDataDir, t, SPLIT_INFO_PATTERN)
+		lastSplitPattern := fmt.Sprintf("%s/%s.%s.[CPD]", metaInfoDataDir, t, LAST_SPLIT_PATTERN)
 
 		doneMatches, _ := filepath.Glob(donePattern)
 		interruptedMatches, _ := filepath.Glob(interruptedPattern)
 		createdMatches, _ := filepath.Glob(createdPattern)
+		lastSplitMatches, _ := filepath.Glob(lastSplitPattern)
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:752]: Exit if `len(lastSplitMatches) > 1`. This will let us know if there is any bug in the implementation.

File: yb-voyager/cmd/importData.go [hunk 5]
```diff
@@ -500,19 +499,21 @@ func splitDataFiles(importTables []string, taskQueue chan *SplitFileImportTask)
...
 		fileFullySplit := false
 		pattern := fmt.Sprintf("%s/%s/data/%s.[0-9]*.[0-9]*.[0-9]*.[CPD]", exportDir, metaInfoDir, t)
 		matches, _ := filepath.Glob(pattern)
-		// in progress are interrupted ones
-		interruptedRegexStr := fmt.Sprintf(".+/%s\\.(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)\\.[P]$", t)
-		interruptedRegexp := regexp.MustCompile(interruptedRegexStr)
+
+		doneSplitRegexStr := fmt.Sprintf(".+/%s\\.(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)\\.[D]$", t)
+		doneSplitRegexp := regexp.MustCompile(doneSplitRegexStr)
+		validTableSplitRegexStr := fmt.Sprintf(".+/%s\\.(\\d+)\\.(\\d+)\\.(\\d+)\\.(\\d+)\\.[CPD]$", t)
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:516]: How about naming it as `regexSplitFileName`?

Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:516]: Can name it as `splitFileNameRegexStr`
currently, all other similar variables names ends with `Regex`, Just following the same pattern here. We can consider renaming to this pattern all variables later.

File: yb-voyager/cmd/importData.go (hunk 4 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:752]: done

File: yb-voyager/cmd/importData.go (hunk 3 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:753]: done

File: yb-voyager/cmd/importData.go (hunk 2 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:541]: Just wanted the check to be strict `*.D`, generated based on the table name.
Your approach should also be fine.

File: yb-voyager/cmd/importData.go (hunk 1 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:383]: done

File: yb-voyager/cmd/importData.go (hunk 4 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:752]: done

File: yb-voyager/cmd/importData.go (hunk 5 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:516]: Is that fine if i name `splitFileNameRegexStr` for now?

**Review by amit-yb — APPROVED** [review]

File: yb-voyager/cmd/importData.go (hunk 5 above)
Comment (amit-yb) [reply yb-voyager/cmd/importData.go]: Yes. You can use the name `splitFileNameRegexStr`.
