### PR TITLE
Fix: nil pointer exception while sending the callhome payload for import data to source/source-replica

### LINKED ISSUE #2364: Fix "invalid memory address or nil pointer dereference" error during sending callhome on exit in import data to source
Jira Link: [DB-15568](https://yugabyte.atlassian.net/browse/DB-15568)

### PR DESCRIPTION
**Pull request by priyanshi-yb**
### Describe the changes in this pull request
Fixing the nil pointer exception while sending the call home payload for exit/error case during initial phase of import data to source/source-replica. 
fixes #2364 

### Describe if there are any user-facing changes

No

### How was this pull request tested?

Manually
### Does your PR have changes that can cause upgrade issues? 
| Component        | Breaking changes? |
| :----------------------------------------------: | :-----------: |
| MetaDB                                                    | No |
| Name registry json                                        | No |
| Data File Descriptor Json                                 | No |
| Export Snapshot Status Json                               | No |
| Import Data State                                         | No |
| Export Status Json                                        | No |
| Data .sql files of tables                                 | No |
| Export and import data queue                              | No |
| Schema Dump                                               | No |
| AssessmentDB                                              | No |
| Sizing DB                                                 |  No |
| Migration Assessment Report Json                          | No |
| Callhome Json                                             | No |
| YugabyteD Tables                                          | No |
| TargetDB Metadata Tables                                  | No |

### CODE REVIEW

File: yb-voyager/cmd/importDataToSource.go [hunk 1]
```diff
@@ -112,7 +114,7 @@ func packAndSendImportDataToSourcePayload(status string, errorMsg string) {
 
 	importDataPayload.Phase = importPhase
 
-	if importPhase != dbzm.MODE_SNAPSHOT {
+	if importPhase != dbzm.MODE_SNAPSHOT && statsReporter != nil {
```
Comment (sanyamsinghal) [inline yb-voyager/cmd/importDataToSource.go:117]: what is the case when statsReporter will be null?

File: yb-voyager/cmd/importDataToSourceReplica.go [hunk 2]
```diff
@@ -100,9 +100,11 @@ func packAndSendImportDataToSrcReplicaPayload(status string, errorMsg string) {
 	payload.MigrationType = LIVE_MIGRATION
 
 	sourceDBDetails := callhome.SourceDBDetails{
-		DBType:    tconf.TargetDBType,
-		DBVersion: targetDBDetails.DBVersion,
```
Comment (sanyamsinghal) [inline yb-voyager/cmd/importDataToSourceReplica.go:104]: same comment as above; use ternary.

File: yb-voyager/cmd/importDataToSource.go (hunk 1 above)
Comment (priyanshi-yb) [reply yb-voyager/cmd/importDataToSource.go:117]: It can be nil until it is initialized. If there is any failure or exit before that, this function will try to send the payload, and we can get a nil pointer exception in such a case.

File: yb-voyager/cmd/importDataToSource.go [hunk 3]
```diff
@@ -98,7 +98,9 @@ func packAndSendImportDataToSourcePayload(status string, errorMsg string) {
 
 	sourceDBDetails := callhome.SourceDBDetails{
 		DBType:    tconf.TargetDBType,
-		DBVersion: targetDBDetails.DBVersion,
+	}
+	if targetDBDetails != nil {
+		sourceDBDetails.DBVersion = targetDBDetails.DBVersion
```
[the remark this answers is not in the document]
Comment (priyanshi-yb) [reply yb-voyager/cmd/importDataToSource.go:103]: can't do this; it doesn't work if we do nil check in this function as it still tries to run the if clause. refer https://go.dev/play/p/sgeATTvMgMP

[the remark this answers is not in the document]
Comment (sanyamsinghal) [reply yb-voyager/cmd/importDataToSource.go:103]: Interesting. 
So this is because Go follows strict/eager evaluation of function argument

File: yb-voyager/cmd/importDataToSource.go (hunk 1 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importDataToSource.go:117]: https://www.honeybadger.io/blog/go-exception-handling/

Comment (makalaaneesh) [reply yb-voyager/cmd/importDataToSource.go:117]: @sanyamsinghal if I understood you correctly, you're suggesting that we have some sort of a try-catch for the exit handlers as a safety net so that they don't panic, is that correct? 

If so, atexit already sort of does that. Check this out:
```
func runHandler(handler func()) {
	defer func() {
		if err := recover(); err != nil {
			fmt.Fprintln(os.Stderr, "error: atexit handler error:", err)
		}
	}()

	handler()
}
```

Comment (priyanshi-yb) [reply yb-voyager/cmd/importDataToSource.go:117]: Yeah right, in this case I am fixing in this PR, it wasn't panicking with stack trace, it was just erroring with below msg
```
error: atexit handler error: runtime error: invalid memory address or nil pointer dereference
```

Comment (sanyamsinghal) [reply yb-voyager/cmd/importDataToSource.go:117]: @makalaaneesh @priyanshi-yb  what i was recommending is that we don't even error out if callhome payload sending failing.
Maybe just log that error, or max to max display on console.

Any failure in sending payload to callhome should not result in an error is what I think

Comment (priyanshi-yb) [reply yb-voyager/cmd/importDataToSource.go:117]: > Maybe just log that error, or max to max display on console.

exit handler also displays the msg on the console for any failure, and the issue we hit is for the exit case only.

Comment (sanyamsinghal) [reply yb-voyager/cmd/importDataToSource.go:117]: maybe i am missing something, lets discuss this overall tomorrow.

**Review by sanyamsinghal — APPROVED** [review]
