### PR TITLE
Enhancement: Retry INDEX creation in case of 'schema version mismatch error'

### LINKED ISSUE #250: `schema version mismatch` from DB while creating index after data import
```
ERROR: Aborted: ERROR:  Query error: schema version mismatch for table 00004005000030008000000000004590: expected 1, got 0 
```

Steps : 
1. Create tables on source with unique index. 
2. Use yb-voyager to export schema followed by data and import schema
3. Perform import data.

Expected : Migration must be successful.
Actual: Error displayed on performing import data

Please find the [Schema and the Error logs here](https://docs.google.com/document/d/1sCHJSAOMUv8KgRlWMQHoizq_RyaC1czq5i-UmUfd6Uc/edit)

### PR DESCRIPTION
**Pull request by sanyamsinghal**
- fixes #250 (note: the error can still appear given index creation doesn't get through even after 5 retries)
    

Tested with a postgres and oracle migration and retries made the error disappear and index creation successful

### CODE REVIEW

File: yb-voyager/cmd/importData.go [hunk 1]
```diff
@@ -933,12 +933,19 @@ func executeSqlFile(file string) {
 
 	var errOccured = 0
 	sqlStrArray := createSqlStrArray(file, "")
-	for _, sqlStr := range sqlStrArray {
+	retryCount := INDEX_RETRY_COUNT
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:936]: Let's not call it as a "index retry count". We're going to retry any DDL statement if it fails with a "retriable" error. For now, the only retriable error that we know of is "Query error: schema version mismatch".

We can call it something like `DDL_STATEMENT_MAX_RETRY_COUNT`.

File: yb-voyager/cmd/importData.go [hunk 2]
```diff
@@ -933,12 +933,19 @@ func executeSqlFile(file string) {
...
+	for i := 0; i < len(sqlStrArray); {
+		sqlStr := sqlStrArray[i]
 		log.Infof("Run query %q on target %q", sqlStr[1], target.Host)
 		_, err := conn.Exec(context.Background(), sqlStr[0])
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:940]: Let's define a separate function `execSQLStatementWithRetries(conn, sql)`. Move the call to the `conn.Exec()` in the new function. The function should take care of retries internally. That should leave the `for _, sqlStr := range sqlStrArray` loop intact.

File: yb-voyager/cmd/importData.go [hunk 3]
```diff
@@ -933,12 +933,19 @@ func executeSqlFile(file string) {
...
 		if err != nil {
-			log.Errorf("Run query %q on target %q: %s", sqlStr[1], target.Host, err)
-			if strings.Contains(err.Error(), "already exists") {
+			log.Errorf("Index creation failed %s", err)
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:942]: Don't assume that this function is called only for "index creation". This function can also be called for sequence creation:
```
	if utils.FileOrFolderExists(sequenceFilePath) {
		fmt.Printf("setting resume value for sequences %10s", "")
		go utils.Wait("done\n", "")
		executeSqlFile(sequenceFilePath)
	}
```

File: yb-voyager/cmd/importData.go [hunk 4]
```diff
@@ -933,12 +933,19 @@ func executeSqlFile(file string) {
...
+			if strings.Contains(strings.ToLower(err.Error()), strings.ToLower(SCHEMA_VERSION_MISMATCH_ERR)) &&
+				retryCount > 0 {
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:944]: Don't update the counters in reverse direction. They are unnecessarily complicated for understanding. Inside the suggested `execSqlStatementWithRetries(conn, sql)` function have a straight-forward loop on retryCount (i.e. `for retryCount := 1; retryCount <= DDL_STATEMENT_MAX_RETRY_COUNT; retryCount++ {`) .

File: yb-voyager/cmd/importData.go [hunk 5]
```diff
@@ -933,12 +933,19 @@ func executeSqlFile(file string) {
...
+				log.Infof("RETRYING INDEX CREATION: %q", sqlStr[0])
+				retryCount--
+				continue
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:947]: No sleep before retrying????

File: yb-voyager/cmd/importData.go [hunk 6]
```diff
@@ -951,11 +958,13 @@ func executeSqlFile(file string) {
 				fmt.Printf("\b \n    %s\n", err.Error())
 				fmt.Printf("    STATEMENT: %s\n", sqlStr[1])
 				if !target.ContinueOnError { //default case
-					fmt.Println(err)
-					os.Exit(1)
+					utils.ErrExit("%v", err)
 				}
 			}
+		} else { // restore the value in case of no error
+			retryCount = INDEX_RETRY_COUNT
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:965]: Once you have the separate function, you won't need such "arbitrary" variable updates...

File: yb-voyager/cmd/importData.go (hunk 1 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:936]: done

File: yb-voyager/cmd/importData.go (hunk 2 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:940]: done

File: yb-voyager/cmd/importData.go [hunk 7]
```diff
@@ -933,17 +933,27 @@ func executeSqlFile(file string) {
...
-		log.Infof("Run query %q on target %q", sqlStr[1], target.Host)
+	for _, sqlStr := range sqlStrArray {
+		executeSqlStmtWithRetries(conn, sqlStr, &errOccured)
+	}
+
+	utils.WaitChannel <- errOccured
+	<-utils.WaitChannel
+}
+
+func executeSqlStmtWithRetries(conn *pgx.Conn, sqlStr []string, errOccured *int) {
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:944]: Instead of taking `errOccured` as an `out` parameter, why not just return `error` and let the caller compute errOccurred based on `err`?

Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go]: @amit-yb did this change. Please have a look

File: yb-voyager/cmd/importData.go [hunk 8]
```diff
@@ -935,34 +935,67 @@ func executeSqlFile(file string) {
...
+	retryCount := 0
+	log.Infof("Run query %q on target %q", sqlInfo.formattedStmtStr, target.Host)
+	for retryCount <= DDL_MAX_RETRY_COUNT {
+		_, err = conn.Exec(context.Background(), sqlInfo.stmt)
+		if err != nil {
+			log.Errorf("DDL Execution Failed %s", err)
+			if strings.Contains(strings.ToLower(err.Error()), strings.ToLower(SCHEMA_VERSION_MISMATCH_ERR)) &&
+				objType == "INDEX" {
+				// creating fresh connection
+				conn, err2 := pgx.Connect(context.Background(), target.GetConnectionUri())
```
[the remark this answers is not in the document]
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:961]: The `conn` variable is first initialised in `executeSqlFile()` caller function where the defer `conn.Close()` call is made. That will close the connection at end
But yeah i should close the current before creating new one. Will do that change.

File: yb-voyager/cmd/importData.go [hunk 9]
```diff
@@ -935,34 +935,67 @@ func executeSqlFile(file string) {
...
+	utils.WaitChannel <- errOccured
+	<-utils.WaitChannel
+}
+
+func executeSqlStmtWithRetries(conn *pgx.Conn, sqlInfo sqlInfo, objType string) error {
+	var err error
+	retryCount := 0
+	log.Infof("Run query %q on target %q", sqlInfo.formattedStmtStr, target.Host)
+	for retryCount <= DDL_MAX_RETRY_COUNT {
+		_, err = conn.Exec(context.Background(), sqlInfo.stmt)
```
[the remark this answers is not in the document]
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:955]: I am creating a new connection in case of that error:
```
if strings.Contains(strings.ToLower(err.Error()), strings.ToLower(SCHEMA_VERSION_MISMATCH_ERR)) &&
objType == "INDEX" {
       // creating fresh connection
       conn, err2 := pgx.Connect(context.Background(), target.GetConnectionUri())
}
```

File: yb-voyager/cmd/importData.go [hunk 10]
```diff
@@ -935,34 +935,67 @@ func executeSqlFile(file string) {
...
+
+	utils.WaitChannel <- errOccured
+	<-utils.WaitChannel
+}
+
+func executeSqlStmtWithRetries(conn *pgx.Conn, sqlInfo sqlInfo, objType string) error {
+	var err error
+	retryCount := 0
+	log.Infof("Run query %q on target %q", sqlInfo.formattedStmtStr, target.Host)
+	for retryCount <= DDL_MAX_RETRY_COUNT {
```
[the remark this answers is not in the document]
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:954]: ok

File: yb-voyager/cmd/importData.go [hunk 11]
```diff
@@ -915,7 +915,7 @@ func doOneImport(task *SplitFileImportTask, connPool *tgtdb.ConnectionPool) {
 	}
 }
 
-func executeSqlFile(file string) {
+func executeSqlFile(file string, objType string) {
 	log.Infof("Execute SQL file %q on target %q", file, target.Host)
 	connectionURI := target.GetConnectionUri()
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:920]: Define a separate function to wrap the code to instantiate a new connection and set schema if required. We can call it something like `newTargetConn()`.
See the other comment to know how can we use it to have a new connection after each error.

File: yb-voyager/cmd/importData.go [hunk 12]
```diff
@@ -935,34 +935,65 @@ func executeSqlFile(file string) {
...
-		_, err := conn.Exec(context.Background(), sqlStr[0])
+	sqlInfoArr := createSqlStrInfoArray(file, objType)
+	for _, sqlInfo := range sqlInfoArr {
+		err := executeSqlStmtWithRetries(conn, sqlInfo, objType)
 		if err != nil {
-			log.Errorf("Run query %q on target %q: %s", sqlStr[1], target.Host, err)
-			if strings.Contains(err.Error(), "already exists") {
+			errOccured = 1
+		}
+	}
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:944]:
```
for _, sqlInfo := range sqlInfoArr {
  if conn == nil {
    conn = newTargetConn()
  }
  err := executeSqlStmtWithRetries(conn, sqlInfo, objType)
  if err != nil {
    conn.Close()
    conn = nil
    errOccured = 1
  }
}
```

File: yb-voyager/cmd/importData.go [hunk 13]
```diff
@@ -935,34 +935,65 @@ func executeSqlFile(file string) {
...
+	var err, err2 error
+	log.Infof("Run query %q on target %q", sqlInfo.formattedStmtStr, target.Host)
+	for retryCount := 0; retryCount <= DDL_MAX_RETRY_COUNT; {
+		_, err = conn.Exec(context.Background(), sqlInfo.stmt)
+		if err != nil {
+			log.Errorf("DDL Execution Failed %s", err)
+			if strings.Contains(strings.ToLower(err.Error()), strings.ToLower(SCHEMA_VERSION_MISMATCH_ERR)) &&
+				objType == "INDEX" {
+				// creating fresh connection
+				conn, err2 = pgx.Connect(context.Background(), target.GetConnectionUri())
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:960]: Note that, setting a `conn` variable here is not going to have any effect of the `conn` in the `executeSqlFile()`.

File: yb-voyager/cmd/importData.go [hunk 14]
```diff
@@ -935,34 +935,65 @@ func executeSqlFile(file string) {
...
+					utils.ErrExit("could not created a connection: %v", err2)
+				}
+
+				// DROP INDEX in case INVALID index got created
+				dropIdxQuery := fmt.Sprintf("DROP INDEX IF EXISTS %s", sqlInfo.objName)
+				log.Infof("Dropping index: %q", dropIdxQuery)
+				_, err2 = conn.Exec(context.Background(), dropIdxQuery)
+				if err2 != nil {
+					utils.ErrExit("Failed in dropping index before retry: %s", sqlInfo.objName)
+				}
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:971]: Extract this snippet in a separate function named as `dropIndex()`. The `dropIndex()` will internally create a connection and also close it before returning.
Use the earlier proposed `newTargetConn()` function which takes care of setting schema as well.

File: yb-voyager/cmd/importData.go [hunk 15]
```diff
@@ -935,34 +935,65 @@ func executeSqlFile(file string) {
...
+	}
+
+	utils.WaitChannel <- errOccured
+	<-utils.WaitChannel
+}
+
+func executeSqlStmtWithRetries(conn *pgx.Conn, sqlInfo sqlInfo, objType string) error {
+	var err, err2 error
+	log.Infof("Run query %q on target %q", sqlInfo.formattedStmtStr, target.Host)
+	for retryCount := 0; retryCount <= DDL_MAX_RETRY_COUNT; {
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:953]: `retryCount` is not incremented anywhere!!!

File: yb-voyager/cmd/importData.go [hunk 16]
```diff
@@ -935,34 +935,65 @@ func executeSqlFile(file string) {
...
 					os.Exit(1)
 				}
 			}
 		}
+		return err // if there is no error or retry scenario then move to next execute next SQL Stmt
 	}
-
-	utils.WaitChannel <- errOccured
-	<-utils.WaitChannel
+	return err
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:996]: What happens when all retries are exhausted? From the current implementation, it looks like it will silently proceed to the next schema creation!! Should it abort if `--continue-on-error` is not set.

File: yb-voyager/cmd/importData.go [hunk 17]
```diff
@@ -935,34 +935,65 @@ func executeSqlFile(file string) {
...
+	utils.WaitChannel <- errOccured
+	<-utils.WaitChannel
+}
+
+func executeSqlStmtWithRetries(conn *pgx.Conn, sqlInfo sqlInfo, objType string) error {
+	var err, err2 error
+	log.Infof("Run query %q on target %q", sqlInfo.formattedStmtStr, target.Host)
+	for retryCount := 0; retryCount <= DDL_MAX_RETRY_COUNT; {
+		_, err = conn.Exec(context.Background(), sqlInfo.stmt)
+		if err != nil {
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:955]: The code will be slightly more readable if you take care of the successful case first. That will reduce indentation level of your code:
```
  _, err = conn.Exec(...)
  if err == nil {
    return nil
  }
  // Proceed to handling error.
```

Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go]: done

File: yb-voyager/cmd/importData.go (hunk 16 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:1004]: done

File: yb-voyager/cmd/importData.go (hunk 14 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go]: done

File: yb-voyager/cmd/importData.go (hunk 13 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go]: done

File: yb-voyager/cmd/importData.go (hunk 12 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go]: done

File: yb-voyager/cmd/importData.go (hunk 11 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go]: done

File: yb-voyager/cmd/importData.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go]: done

File: yb-voyager/cmd/importData.go [hunk 18]
```diff
@@ -915,54 +896,112 @@ func doOneImport(task *SplitFileImportTask, connPool *tgtdb.ConnectionPool) {
...
+	_, err := (*conn).Exec(context.Background(), dropIdxQuery)
+	if err != nil {
+		utils.ErrExit("Failed in dropping index: %s", idxName)
+	}
+}
+
+func executeSqlFile(file string, objType string) {
+	log.Infof("Execute SQL file %q on target %q", file, target.Host)
+
+	conn := newTargetConn()
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:933]: Nit: This is not needed. The `for` loop will take care of creating a new connection on the first iteration.

File: yb-voyager/cmd/importData.go [hunk 19]
```diff
@@ -915,54 +896,112 @@ func doOneImport(task *SplitFileImportTask, connPool *tgtdb.ConnectionPool) {
...
+	defer conn.Close(context.Background())
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:934]: If `conn` is set to `nil` on the last iteration of the `for` loop, this call will panic with `nil pointer dereference` error.
```
defer func() {
  if conn != nil {
    conn.Close(context.Background())
  }
}()
```

File: yb-voyager/cmd/importData.go [hunk 20]
```diff
@@ -915,54 +896,112 @@ func doOneImport(task *SplitFileImportTask, connPool *tgtdb.ConnectionPool) {
...
 
 	var errOccured = 0
-	sqlStrArray := createSqlStrArray(file, "")
-	for _, sqlStr := range sqlStrArray {
-		log.Infof("Run query %q on target %q", sqlStr[1], target.Host)
-		_, err := conn.Exec(context.Background(), sqlStr[0])
+	sqlInfoArr := createSqlStrInfoArray(file, objType)
+	for _, sqlInfo := range sqlInfoArr {
+		if conn == nil {
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:939]: This looks much cleaner now 👍 .

File: yb-voyager/cmd/importData.go [hunk 21]
```diff
@@ -915,54 +896,112 @@ func doOneImport(task *SplitFileImportTask, connPool *tgtdb.ConnectionPool) {
...
+			log.Infof("Sleep for 5 seconds before retrying for %dth time", retryCount)
+			time.Sleep(time.Second * 5)
+			log.Infof("RETRYING DDL: %q", sqlInfo.stmt)
+
+			if retryCount == DDL_MAX_RETRY_COUNT {
+				fmt.Printf("\b \n    %s\n", err.Error())
+				fmt.Printf("    STATEMENT: %s\n", sqlInfo.formattedStmtStr)
+				if !target.ContinueOnError {
+					os.Exit(1)
 				}
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:982]: This code snippet is duplicated thrice in this function. Move it at the bottom of the function--just before returning `err`. Something like:
```
	for ... {
		_, err = conn.Exec(...)
		if err is retriable {
			// Create new conn.
			// Drop index.
			// Sleep.
            continue
		}
		// Non retriable errors.
		if "already exist?" && arget.IgnoreIfExists {
			err = nil  // Ignore error.
		}
		break

	}
	if err != nil {
		fmt.Printf("\b \n    %s\n", err.Error())
		fmt.Printf("    STATEMENT: %s\n", sqlInfo.formattedStmtStr)
		if !target.ContinueOnError {
			os.Exit(1)
		}
	}
	return err
```

File: yb-voyager/cmd/importData.go [hunk 22]
```diff
@@ -915,54 +896,112 @@ func doOneImport(task *SplitFileImportTask, connPool *tgtdb.ConnectionPool) {
...
 		utils.ErrExit("connect to target db: %s", err)
 	}
-	defer conn.Close(context.Background())
 
+	setTargetSchema(conn)
+	return conn
+}
+
+func setTargetSchema(conn *pgx.Conn) {
 	if sourceDBType != POSTGRESQL && target.Schema != YUGABYTEDB_DEFAULT_SCHEMA {
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:912]: Negating this condition will make it more readable (remember the `De Morgan's Theorem`?? 🙂 ):
```
  if sourceDBType == POSTGRESQL || target.Schema == YUGABYTEDB_DEFAULT_SCHEMA {
    // For PG, schema name is already included in the object name.
    // No need to set schema if importing in the default schema.
    return
  }
  // Proceed to running SET SCHEMA.
```

File: yb-voyager/cmd/importData.go [hunk 23]
```diff
@@ -915,54 +896,112 @@ func doOneImport(task *SplitFileImportTask, connPool *tgtdb.ConnectionPool) {
...
 		if err != nil {
 			utils.ErrExit("run query %q on target %q: %s", setSchemaQuery, target.Host, err)
 		}
 	}
+}
+
+func dropIdx(conn *pgx.Conn, idxName string) {
+	dropIdxQuery := fmt.Sprintf("DROP INDEX IF EXISTS %s", idxName)
+	log.Infof("Dropping index: %q", dropIdxQuery)
+	_, err := (*conn).Exec(context.Background(), dropIdxQuery)
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:924]: No need of dereferencing the `conn` pointer in the `(*conn).Exec`. Just `conn.Exec()` is sufficient.

File: yb-voyager/cmd/importData.go [hunk 24]
```diff
@@ -915,54 +896,112 @@ func doOneImport(task *SplitFileImportTask, connPool *tgtdb.ConnectionPool) {
...
+	if err != nil {
+		utils.ErrExit("Failed in dropping index: %s", idxName)
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:926]: Include `err` in the message.

File: yb-voyager/cmd/importData.go (hunk 23 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:924]: oh ok, that because its a struct

File: yb-voyager/cmd/importData.go (hunk 22 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:912]: Yeah nice reference.

File: yb-voyager/cmd/importData.go (hunk 21 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:982]: @amit-yb soon we are going to move to new import data code path. Is this change really needed, I was thinking of doing something similar but didn't want to add work

File: yb-voyager/cmd/importData.go (hunk 23 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:924]: done

File: yb-voyager/cmd/importData.go (hunk 24 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:926]: done

File: yb-voyager/cmd/importData.go (hunk 21 above)
Comment (amit-yb) [reply yb-voyager/cmd/importData.go:990]: New import path uses the same code path for importing sequences and indexes. So yes, we need to make this change.

Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:990]: ok cool, will do this then

File: yb-voyager/cmd/importData.go [hunk 25]
```diff
@@ -915,54 +896,123 @@ func doOneImport(task *SplitFileImportTask, connPool *tgtdb.ConnectionPool) {
...
+	}
+}
+
+func executeSqlFile(file string, objType string) {
+	log.Infof("Execute SQL file %q on target %q", file, target.Host)
+
+	conn := newTargetConn()
+	defer func() {
+		if conn != nil {
+			defer conn.Close(context.Background())
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:940]: You're already in the `defer` context!!! Drop the `defer` keyword from this statement.

**Review by amit-yb — APPROVED** [review]
Thanks for patiently addressing all the review comments 👍 .
