### PR TITLE
Convert schema names to case-insensitive during import schema

### LINKED ISSUE #334: [MYSQL] --target-db-schema flag fails for case sensitive schema names
If we create a schema in the YB side with a case sensitive name, and pass the env variable with the same, the `import schema` fails with error.

Steps to reproduce:

1. Create a schema on the target with case sensitive name example: XYZ, Xyz.
2. Pass the same in the env variable of `TARGET_DB_SCHEMA`.
3. Try importing into that schema using the `--target-db-schema` flag.

Corresponding error:

Image

### PR DESCRIPTION
**Pull request by rahulb-yb**
[Fixes #334, #335, #336]
Voyager now converts any case sensitive names for target schema to lowercase. The user can convert the schema names to case-sensitive names post import using alter statements, if needed

### CODE REVIEW

File: yb-voyager/src/utils/utils.go [hunk 1]
```diff
@@ -304,3 +304,13 @@ func InsensitiveSliceContains(slice []string, s string) bool {
 	log.Infof("string s=%q did not match with any string in %v", s, slice)
 	return false
 }
+
+func ToInsensitiveSlice(slice []string) []string {
```
Comment (amit-yb) [inline yb-voyager/src/utils/utils.go:308]: Nit: `ToCaseInsensitiveNames(names []string)`.

File: yb-voyager/src/utils/utils.go [hunk 2]
```diff
@@ -304,3 +304,13 @@ func InsensitiveSliceContains(slice []string, s string) bool {
...
+	for i, object := range slice {
+		if IsQuotedString(object) {
```
Comment (amit-yb) [inline yb-voyager/src/utils/utils.go:310]: Nit: This check is not required. For unquoted string, the `Trim()` call will be no-op.

**Review by amit-yb — APPROVED** [review]
