### PR TITLE
Added FixedIn version for issues fixed in the 2.25 YB version

### LINKED ISSUE #2209: Support 2.25 for assess-migration and analyze-schema and updated issues fixed in version
Jira Link: [DB-14947](https://yugabyte.atlassian.net/browse/DB-14947)

### PR DESCRIPTION
**Pull request by priyanshi-yb**
### Describe the changes in this pull request
- Supporting the `2.25` YB version by adding the fixed in version to the issues fixed in the YB 2.25 release https://docs.yugabyte.com/preview/develop/pg15-features/
fixes #2209 
The following issues are fixed in - 
1. Stored generated columns
2. Before Row triggers on partitioned tables
3. Multi-range datatypes
4. Security invoker issues
5. Deterministic attribute with CREATE COLLATION
6. Foreign key references to partitioned tables
7. SQL body in function
8. Unique Nulls Not distinct
9. Regex functions
10. Range aggregate functions 
11. Jsonb subscripting
12. Copy FROM .. WHERE
13. CTE with Materialized clause

- Separated out the `any_value`, and `range_.._agg` aggregate functions into two separate issues: range functions are PG15 feature and fixed in 2.25 release and any_value is PG16 feature.
- 
### Describe if there are any user-facing changes

Fixed issues won't be reported if target-db-version is 2.25 and in the other case the report will show the fixed version for the issue 
### How was this pull request tested?

current tests should be enough

### Does your PR have changes that can cause upgrade issues? 
| Component        | Breaking changes? |
| :----------------------------------------------: | :-----------: |
| MetaDB                                                    | No |
| Name registry json                                        | No |
| Data File Descriptor Json                                 | No |
| Export Snapshot Status Json                               | No |
| Import Data State                                         | No |
| Export Status Json                                        | No |
| Data .sql files of tables                                 | No |
| Export and import data queue                              | No |
| Schema Dump                                               | No |
| AssessmentDB                                              | No |
| Sizing DB                                                 | No |
| Migration Assessment Report Json                          | No |
| Callhome Json                                             | No |
| YugabyteD Tables                                          | No |
| TargetDB Metadata Tables                                  | No |

### CODE REVIEW

File: yb-voyager/src/query/queryissue/issues_ddl.go [hunk 1]
```diff
@@ -540,6 +555,10 @@ var deterministicOptionCollationIssue = issue.Issue{
 	Suggestion:  "This feature is not supported in YugabyteDB yet",
 	GH:          "https://github.com/yugabyte/yugabyte-db/issues/25575",
 	DocsLink:    "https://docs.yugabyte.com/preview/yugabyte-voyager/known-issues/postgresql/#postgresql-12-and-later-features",
+	MinimumVersionsFixedIn: map[string]*ybversion.YBVersion{
+		ybversion.SERIES_2_25: ybversion.V2_25_0_0, // TODO: understand why docs says coming soon non-deterministic collation but the CREATE COLLAITON works on 2.25
```
Comment (makalaaneesh) [inline yb-voyager/src/query/queryissue/issues_ddl.go:559]: If we don't have clarity, i would err on the side of reporting the issue, and then later fixing it, rather than marking it as fixed.

File: yb-voyager/src/query/queryissue/issues_ddl_test.go [hunk 2]
```diff
@@ -341,6 +360,39 @@ func testUniqueNullsNotDistinctIssue(t *testing.T) {
 	assertErrorCorrectlyThrownForIssueForYBVersion(t, err, "syntax error", uniqueNullsNotDistinctIssue)
 }
 
+func testBeforeRowTriggerOnPartitionedTable(t *testing.T) {
```
Comment (makalaaneesh) [inline yb-voyager/src/query/queryissue/issues_ddl_test.go:363]: was this just a miss?

File: yb-voyager/src/query/queryissue/issues_dml.go [hunk 3]
```diff
@@ -228,6 +255,9 @@ var cteWithMaterializedIssue = issue.Issue{
 	Suggestion:  "No workaround available right now",
 	GH:          "https://github.com/yugabyte/yugabyte-db/issues/25575",
 	DocsLink:    "https://docs.yugabyte.com/preview/yugabyte-voyager/known-issues/postgresql/#postgresql-12-and-later-features",
+	MinimumVersionsFixedIn: map[string]*ybversion.YBVersion{
+		ybversion.SERIES_2_25:   ybversion.V2_25_0_0, //TODO: understand in NOT MATERIALIZED works as expected internally
```
Comment (makalaaneesh) [inline yb-voyager/src/query/queryissue/issues_dml.go:259]: let's discuss this

File: yb-voyager/src/query/queryissue/issues_dml_test.go [hunk 4]
```diff
@@ -108,9 +138,38 @@ func testCopyFromWhereIssue(t *testing.T) {
 	conn, err := getConn()
 	assert.NoError(t, err)
 
+	tmpFile, err := os.CreateTemp("/tmp", "copy_where_example.csv")
```
Comment (makalaaneesh) [inline yb-voyager/src/query/queryissue/issues_dml_test.go:141]: I just wrote a `CreateTempFile` in testutils. See if we can use that?

File: yb-voyager/src/query/queryissue/constants.go [hunk 5]
```diff
@@ -49,8 +49,11 @@ const (
 	FOREIGN_TABLE                                  = "FOREIGN_TABLE"
 	INHERITANCE                                    = "INHERITANCE"
 
-	AGGREGATE_FUNCTION             = "AGGREGATE_FUNCTION"
-	AGGREGATION_FUNCTIONS_NAME     = "Aggregate Functions"
+	ANY_VALUE_AGGREGATE_FUNCTION      = "ANY_VALUE_AGGREGATE_FUNCTION"
```
[the remark this answers is not in the document]
Comment (priyanshi-yb) [reply yb-voyager/src/query/queryissue/constants.go:52]: yeah will it to the PR description, but the reason for separating it out is that `any_value` is a PG16 feature and range_agg.. functions are PG15 ones and are supported in 2.25 
so we have to add the version for range ones only. So I thought it would be better to separate them now.

File: yb-voyager/src/query/queryissue/issues_ddl_test.go (hunk 2 above)
Comment (priyanshi-yb) [reply yb-voyager/src/query/queryissue/issues_ddl_test.go:363]: the issue was PG12 feature and added before we had this issues-intergrations pipeline so we didn't had the test case for it but this is fixed in 2.25 as I can see on the docs, so added test case and marked it as fixed.

File: yb-voyager/src/query/queryissue/issues_dml_test.go (hunk 4 above)
Comment (priyanshi-yb) [reply yb-voyager/src/query/queryissue/issues_dml_test.go:141]: Will take a look

File: yb-voyager/src/query/queryissue/issues_ddl_test.go (hunk 2 above)
Comment (makalaaneesh) [reply yb-voyager/src/query/queryissue/issues_ddl_test.go:363]: Awesome thanks!

File: yb-voyager/src/query/queryissue/issues_ddl.go (hunk 1 above)
Comment (makalaaneesh) [reply yb-voyager/src/query/queryissue/issues_ddl.go:559]: As discussed in standup, anything is fine, since you have already marked them as fixed, it should be okay 👍

File: yb-voyager/src/query/queryissue/issues_dml.go [hunk 6]
```diff
@@ -73,28 +74,48 @@ var regexFunctionsIssue = issue.Issue{
...
+	return newQueryIssue(anyValueAggregateFunction, objectType, objectName, sqlStatement, map[string]interface{}{})
+}
+
+var rangeAggregateFunctionIssue = issue.Issue{
+	Type:        RANGE_AGGREGATE_FUNCTION,
+	Name:        RANGE_AGGREGATE_FUNCTION_NAME,
+	Impact:      constants.IMPACT_LEVEL_2,
+	Description: RANGE_AGGREGATE_FUNCTION_ISSUE_DESCRIPTION,
+	Suggestion:  "",
+	GH:          "https://github.com/yugabyte/yugabyte-db/issues/25575",
```
Comment (makalaaneesh) [inline yb-voyager/src/query/queryissue/issues_dml.go:106]: we should create separate GH as well then

Comment (priyanshi-yb) [reply yb-voyager/src/query/queryissue/issues_dml.go:106]: we don't have separate GH for PG15-17 issues as we had decided to have a single GH and docs link for these features

**Review by sanyamsinghal — APPROVED** [review]
took a quick look, LGTM. 
Lets wait for @makalaaneesh approval before merge.

**Review by makalaaneesh — APPROVED** [review]
