### PR TITLE
Report all the unsupported datatypes cases in assessment as per the target-db-version

### LINKED ISSUE #2458: Regression: For some of assessment issues we are not filtering if provided fixed yb version
Jira Link: [DB-16018](https://yugabyte.atlassian.net/browse/DB-16018)

### PR DESCRIPTION
**Pull request by priyanshi-yb**
### Describe the changes in this pull request
fixes #2458 

### Describe if there are any user-facing changes

Yes, some datatypes supported in 2.25 version will not be reported if assessment is run against that.

### How was this pull request tested?

Added test for the assessment-report-test schema to run with target-db-version 2.25.0.0 

### Does your PR have changes in callhome/yugabyted payloads? If so, is the payload version incremented?

no

### Does your PR have changes that can cause upgrade issues? 
| Component        | Breaking changes? |
| :----------------------------------------------: | :-----------: |
| MetaDB                                                    | No |
| Name registry json                                        | No |
| Data File Descriptor Json                                 | No |
| Export Snapshot Status Json                               | No |
| Import Data State                                         | No |
| Export Status Json                                        | No |
| Data .sql files of tables                                 | No |
| Export and import data queue                              | No |
| Schema Dump                                               | No |
| AssessmentDB                                              | No |
| Sizing DB                                                 | No |
| Migration Assessment Report Json                          | No |
| Callhome Json                                             | No |
| YugabyteD Tables                                          | No |
| TargetDB Metadata Tables                                  | No |

### CODE REVIEW

File: yb-voyager/cmd/assessMigrationCommand.go [hunk 1]
```diff
@@ -1410,12 +1411,20 @@ func getAssessmentIssuesForUnsupportedDatatypes(unsupportedDatatypes []utils.Tab
...
-			issue = convertAnalyzeSchemaIssueToAssessmentIssue(convertedAnalyzeIssue, queryissue.MinimumVersionsFixedIn)
+			fixed, err := queryissue.IsFixedIn(targetDbVersion)
+			if err != nil {
+				log.Warnf("checking if issue %v is supported: %v", queryissue, err)
+			}
+			if !fixed {
+				convertedAnalyzeIssue := convertIssueInstanceToAnalyzeIssue(queryissue, "", false, false)
+				issue = convertAnalyzeSchemaIssueToAssessmentIssue(convertedAnalyzeIssue, queryissue.MinimumVersionsFixedIn)
+				assessmentIssues = append(assessmentIssues, issue)
+			}
```
Comment (sanyamsinghal) [inline yb-voyager/cmd/assessMigrationCommand.go:1422]: Looks like this is used at multiple places.
Might be worth making this code as a separate function?

**Review by sanyamsinghal — APPROVED** [review]
LGTM.
Thanks for adding that test.
