### PR TITLE
Fix: Clean Table list and Sequences related params in Migration Status Record on startClean

### LINKED ISSUE #2391: [Voyager] Fix discrepancy between stmt and formattedStmt in checkStmtsUsingParser function when detecting UNSUPPORTED_PG_SYNTAX_ISSUE_TYPE
Jira Link: [DB-15661](https://yugabyte.atlassian.net/browse/DB-15661)
### Description

Fix discrepancy between stmt and formattedStmt in checkStmtsUsingParser function when detecting UNSUPPORTED_PG_SYNTAX_ISSUE_TYPE

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [x] I confirm this issue does not contain any sensitive information.

### LINKED ISSUE #2397: Clean the table-list info from the MSR on start-clean
Jira Link: [DB-15724](https://yugabyte.atlassian.net/browse/DB-15724)

### PR DESCRIPTION
**Pull request by priyanshi-yb**
### Describe the changes in this pull request
1. Fixes #2397 , cleaning the table list and sequences related flags in the Migration status record.
2. Fixes #2391 , using the `formattedStmt` in `Parse` of analyze-schema and the `Parse` of the `queryissue.ParseRequiredDDLStmts` functions.

### Describe if there are any user-facing changes

no
### How was this pull request tested?

Manually

### Does your PR have changes that can cause upgrade issues? 
| Component        | Breaking changes? |
| :----------------------------------------------: | :-----------: |
| MetaDB                                                    | No |
| Name registry json                                        | No |
| Data File Descriptor Json                                 | No |
| Export Snapshot Status Json                               | No |
| Import Data State                                         | No |
| Export Status Json                                        | No |
| Data .sql files of tables                                 | No |
| Export and import data queue                              | No |
| Schema Dump                                               | No |
| AssessmentDB                                              | No |
| Sizing DB                                                 | No |
| Migration Assessment Report Json                          | No |
| Callhome Json                                             | No |
| YugabyteD Tables                                          | No |
| TargetDB Metadata Tables                                  | No |

### CODE REVIEW

File: yb-voyager/cmd/exportDataDebezium.go [hunk 1]
```diff
@@ -246,7 +246,7 @@ func fetchOrRetrieveColToSeqMap(msr *metadb.MigrationStatusRecord, tableList []s
 	case TARGET_DB_EXPORTER_FB_ROLE, TARGET_DB_EXPORTER_FF_ROLE:
 		storedColToSeqMap = msr.TargetColumnToSequenceMapping
 	}
-	if storedColToSeqMap != nil {
+	if storedColToSeqMap != nil && !bool(startClean) {
```
Comment (makalaaneesh) [inline yb-voyager/cmd/exportDataDebezium.go:249]: why do we need to check startClean again here? It's already been cleaned up, no?

File: yb-voyager/cmd/exportData.go [hunk 2]
```diff
@@ -1353,6 +1353,12 @@ func clearMigrationStateIfRequired() {
 			utils.ErrExit("Failed to remove name registry file: %s", err)
 		}
 
+		err = metaDB.UpdateMigrationStatusRecord(func(record *metadb.MigrationStatusRecord) {
+			record.TableListExportedFromSource = nil
```
Comment (makalaaneesh) [inline yb-voyager/cmd/exportData.go:1357]: what about the Target* fields? start-clean export-data means everything starts afresh, so I guess we should clean those fields up  as well?

Comment (priyanshi-yb) [reply yb-voyager/cmd/exportData.go:1357]: it's not required to do this as there is no way after the cutover to target to do `export data --start-clean t` as they have to start a new migration altogether but still I have added a few more to this.

File: yb-voyager/cmd/exportDataDebezium.go (hunk 1 above)
Comment (priyanshi-yb) [reply yb-voyager/cmd/exportDataDebezium.go:249]: yeah its not required but for correctness, I have added as for start clean we don't want to use the MSR one.

File: yb-voyager/cmd/exportData.go (hunk 2 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/exportData.go:1357]: I think we might be already using or need this for other commands also.
can we organise this separately


```
metaDB.UpdateMigrationStatsRecord_StartCleanExportSchema()
metaDB.UpdateMigrationStatsRecord_StartCleanExportData()
metaDB.UpdateMigrationStatsRecord_StartCleanImportSchema()
metaDB.UpdateMigrationStatsRecord_StartCleanImportData()...
```

File: yb-voyager/cmd/analyzeSchema.go [hunk 3]
```diff
@@ -324,7 +324,7 @@ func addSummaryDetailsForIndexes() {
 
 func checkStmtsUsingParser(sqlInfoArr []sqlInfo, fpath string, objType string) {
 	for _, sqlStmtInfo := range sqlInfoArr {
-		_, err := queryparser.Parse(sqlStmtInfo.stmt)
+		_, err := queryparser.Parse(sqlStmtInfo.formattedStmt)
```
Comment (sanyamsinghal) [inline yb-voyager/cmd/analyzeSchema.go:327]: was there any issue with stmt (unformmated) one being used before.

Moreover I think formattedStmt is safer choice, since originally it is present in that form, we do the unformmating by concat the string without newlines

Comment (priyanshi-yb) [reply yb-voyager/cmd/analyzeSchema.go:327]: > was there any issue with stmt (unformmated) one being used before.

Not that I know of, but there was a discrepancy in this Parse() call and another call of it in the `ParseRequiredDDLs`, where we are using the `formattedStmt` so just to maintain consistency in both I have changed so that even if formattedStmt has some issue this `Parse` should catch it.

File: yb-voyager/cmd/exportData.go (hunk 2 above)
Comment (priyanshi-yb) [reply yb-voyager/cmd/exportData.go:1357]: Can we do this in a separate PR after analyzing all other Fields in MSR we want to cleanup for other commands? If so I create a ticket and will pick it up separately.

Comment (sanyamsinghal) [reply yb-voyager/cmd/exportData.go:1357]: yeah sure. 
Maybe create a new ticket and link it with tech debt one you created the other day.

**Review by sanyamsinghal — APPROVED** [review]
lgtm
