### PR TITLE
Modified sql parsing logic to work for any kind of SQL in a .sql file

### LINKED ISSUE #355: [MYSQL] Import schema for auto-generated column fails after Ora2Pg commit
This is the original ticket
[#315](https://github.com/yugabyte/yb-voyager/issues/315)

So an issue was put up on Ora2Pg and they implemented migration of auto-generated columns using triggers.
[Commit](https://github.com/darold/ora2pg/commit/59028d196fbde077af7f158b3afb33ebe54f0e2a)

But now the `import-schema` fails with error.

**Original schema:**

```
CREATE TABLE auto_price (
	id INT,
	first_name VARCHAR(50),
	gender VARCHAR(50),
	price_dollar DECIMAL(7,2),
    price_pound DECIMAL(7,2) GENERATED ALWAYS AS (price_dollar * 0.22) STORED
);
```

**Previously exported schema:**

```
CREATE TABLE auto_price (
	id bigint,
	first_name varchar(50),
	gender varchar(50),
	price_dollar decimal(7,2),
	price_pound decimal(7,2)
) ;
```

**Exported schema after commit:**

```
CREATE TABLE auto_price (
	id bigint,
	first_name varchar(50),
	gender varchar(50),
	price_dollar decimal(7,2),
	price_pound decimal(7,2)
) ;
DROP TRIGGER IF EXISTS virt_col_auto_price_trigger ON auto_price CASCADE;

CREATE OR REPLACE FUNCTION fct_virt_col_auto_price_trigger() RETURNS trigger AS $BODY$
BEGIN
	NEW.price_pound = (NEW.price_dollar * 0.22);

RETURN NEW;
end
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;

CREATE TRIGGER virt_col_auto_price_trigger
        BEFORE INSERT OR UPDATE ON auto_price FOR EACH ROW
        EXECUTE PROCEDURE fct_virt_col_auto_price_trigger();


```

**Error while importing:**

```
importing      TABLE      
    ERROR: unterminated dollar-quoted string at or near "$BODY$ BEGIN 	NEW.price_pound = (NEW.price_dollar * 0.22); " (SQLSTATE 42601)
    STATEMENT: CREATE OR REPLACE FUNCTION fct_virt_col_auto_price_trigger() RETURNS trigger AS $BODY$
BEGIN
	NEW.price_pound = (NEW.price_dollar * 0.22);
ERROR: unterminated dollar-quoted string at or near "$BODY$ BEGIN 	NEW.price_pound = (NEW.price_dollar * 0.22); " (SQLSTATE 42601)
```

### PR DESCRIPTION
**Pull request by sanyamsinghal**
- Fixes #355

### CODE REVIEW

File: yb-voyager/cmd/analyzeSchema.go [hunk 1]
```diff
@@ -584,32 +575,26 @@ func createSqlStrInfoArray(path string, objType string) []sqlInfo {
...
-			if dollarQuoteFlag == 2 {
-				if strings.Contains(curr, ";") {
-					processCollectedSql(path, &singleLine, &singleString, objType, &sqlInfoArr, &reportNextSql)
-					//reset for parsing other sqls
-					dollarQuoteFlag = 0
-					outerDollarQuotedStr = ""
-				}
+		} else if dollarQuoteFlag == 1 {
+			if strings.Contains(curr, outerDollarQuotedStr) {
+				dollarQuoteFlag = 2 //denotes end of code/body part
```
Comment (amit-yb) [inline yb-voyager/cmd/analyzeSchema.go:589]: We can get rid of the `dollarQuoteFlag == 2` case by moving block from line 593-599 to line 589.
That will leave only two valid values, 0 and 1, for the `dollarQuoteFlag`. In that case, we can change its type to `bool` and perhaps name it as `insideCodeBlock`.
Then you can simplify the if..else block as:
```
if !insideCodeBlock {

} else {
    // insideCodeBlock
}
```

File: yb-voyager/cmd/analyzeSchema.go [hunk 2]
```diff
@@ -584,32 +575,26 @@ func createSqlStrInfoArray(path string, objType string) []sqlInfo {
...
-					dollarQuoteFlag = 2 //denotes end of code/body part
-				}
+		// Assuming that both the dollar quote strings will not be in same line
+		if dollarQuoteFlag == 0 {
+			if idx := dollarQuoteRegex.FindStringSubmatch(curr); idx != nil {
+				dollarQuoteFlag = 1 //denotes start of the code/body part
+				outerDollarQuotedStr = idx[0]
+			} else if strings.Contains(curr, ";") { // in case, there is no body part
+				//one liner sql string created, now will check for obj count and report cases
+				processCollectedSql(path, &singleLine, &singleString, objType, &sqlInfoArr, &reportNextSql)
```
Comment (amit-yb) [inline yb-voyager/cmd/analyzeSchema.go:585]: Let's rename `singleLine` as `stmt` and `singleString` as `formattedStmt` to align it with the `sqlInfo` definition.

File: yb-voyager/cmd/analyzeSchema.go [hunk 3]
```diff
@@ -584,32 +575,26 @@ func createSqlStrInfoArray(path string, objType string) []sqlInfo {
...
-					//one liner sql string created, now will check for obj count and report cases
-					processCollectedSql(path, &singleLine, &singleString, objType, &sqlInfoArr, &reportNextSql)
-				}
-			} else if dollarQuoteFlag == 1 {
-				if strings.Contains(curr, outerDollarQuotedStr) {
-					dollarQuoteFlag = 2 //denotes end of code/body part
-				}
+		// Assuming that both the dollar quote strings will not be in same line
+		if dollarQuoteFlag == 0 {
+			if idx := dollarQuoteRegex.FindStringSubmatch(curr); idx != nil {
```
Comment (amit-yb) [inline yb-voyager/cmd/analyzeSchema.go:580]: Rename `idx` as `matches`.

File: yb-voyager/cmd/analyzeSchema.go [hunk 4]
```diff
@@ -584,32 +575,26 @@ func createSqlStrInfoArray(path string, objType string) []sqlInfo {
...
+				dollarQuoteFlag = 1 //denotes start of the code/body part
+				outerDollarQuotedStr = idx[0]
```
Comment (amit-yb) [inline yb-voyager/cmd/analyzeSchema.go:582]: Consider renaming `outerDollarQuotedStr` as `codeBlockDelimiter`.

File: yb-voyager/cmd/analyzeSchema.go [hunk 5]
```diff
@@ -584,32 +575,26 @@ func createSqlStrInfoArray(path string, objType string) []sqlInfo {
...
+			} else if strings.Contains(curr, ";") { // in case, there is no body part
```
Comment (amit-yb) [inline yb-voyager/cmd/analyzeSchema.go:583]: Consider renaming `curr` as just `line` or `currLine`. BTW, (you might already know this), VS Code does provide very easy command to automatically rename all occurrences.

**Review by amit-yb — COMMENTED** [review]
The changes looks okay functionally. Just a few comments to make the code more readable.

File: yb-voyager/cmd/analyzeSchema.go (hunk 4 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/analyzeSchema.go:582]: I used `outer` because it is possible that two nested Blocks are there.
How is `mainCodeBlockDelimiter` or `outerCodeBlockDelimiter` ?

File: yb-voyager/cmd/analyzeSchema.go (hunk 5 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/analyzeSchema.go:583]: Ok will do that, yeah yeah I use that only

File: yb-voyager/cmd/analyzeSchema.go (hunk 4 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/analyzeSchema.go:582]: done

File: yb-voyager/cmd/analyzeSchema.go (hunk 1 above)
Comment (sanyamsinghal) [reply yb-voyager/cmd/analyzeSchema.go:589]: No we can't do that, i have thought of this. But sometimes there are some clause like `LANGUAGE PL/PGSQL` after the ending of Code Block and before the end of functions stmt. Basically multiple lines are possible after Code block but before ending of function 

So that is covered in current way of implemented but not this.

Comment (amit-yb) [reply yb-voyager/cmd/analyzeSchema.go:595]: Got it! 👍

**Review by amit-yb — APPROVED** [review]
LGTM. 👍
