### PR TITLE
Fix: value converter and schema registry should look for table in table list

### LINKED ISSUE #3063: Import data (offline) errors out in case tables are not present on target when export is done via Debezium
Jira Link: [DB-18305](https://yugabyte.atlassian.net/browse/DB-18305)

### PR DESCRIPTION
**Pull request by priyanshi-yb**
… created in target

fixes #3063 

### Does your PR have changes that can cause upgrade issues? 
| Component        | Breaking changes? |
| :----------------------------------------------: | :-----------: |
| MetaDB                                                    |  Yes/No |
| Name registry json                                        |  Yes/No |
| Data File Descriptor Json                                 |  Yes/No |
| Export Snapshot Status Json                               |  Yes/No |
| Import Data State                                         |  Yes/No |
| Export Status Json                                        |  Yes/No |
| Data .sql files of tables                                 |  Yes/No |
| Export and import data queue                              |  Yes/No |
| Schema Dump                                               |  Yes/No |
| AssessmentDB                                              |  Yes/No |
| Sizing DB                                                 |  Yes/No |
| Migration Assessment Report Json                          |  Yes/No |
| Callhome Json                                             |  Yes/No |
| YugabyteD Tables                                          |  Yes/No |
| TargetDB Metadata Tables                                  |  Yes/No |

### CODE REVIEW

**Review by makalaaneesh — APPROVED** [review]
LGTM!

File: yb-voyager/src/namereg/namereg.go [hunk 1]
```diff
@@ -320,12 +320,22 @@ In case both the source and target not present for the table this will return er
 */
 
 func (reg *NameRegistry) LookupTableNameAndIgnoreIfTargetNotFound(tableNameArg string) (sqlname.NameTuple, error) {
```
Comment (makalaaneesh) [inline yb-voyager/src/namereg/namereg.go:322]: LookupTableNameAndIgnoreIfTargetNotFoundBasedOnRole

**Review by makalaaneesh — APPROVED** [review]
LGTM
