### PR TITLE
Bug fix #195: Now comparing the target.Host IPs with the resolved IPs of the host provided by yb_servers() function

### LINKED ISSUE #195: Bug: False Load Balancer Detection
LB is detected as true by `yb-voyager` in case if the output of `yb_servers()` function contains a DNS name in place of actual IPs
For example:
```
yugabyte=# select * from yb_servers();
    host    | port | num_connections | node_type | cloud  |   region    | zone  | public_ip
------------+------+-----------------+-----------+--------+-------------+-------+------------
 localhost3 | 5433 |               0 | primary   | cloud1 | datacenter1 | rack1 | localhost3
 localhost2 | 5433 |               0 | primary   | cloud1 | datacenter1 | rack1 | localhost2
 localhost  | 5433 |               0 | primary   | cloud1 | datacenter1 | rack1 | localhost
(3 rows)
```

### PR DESCRIPTION
**Pull request by sanyamsinghal**
Fix the bug as mentioned in Issue #195 

Testing/Verification Details:
1. Testing with a local cluster of 3 nodes with localhost, localhost2, localhost3 DNSs defined in `/etc/hosts` file
2. `ns.LookUpIP("172.3.21.10")` function for some given IP Addr returns the same IP Addr i.e. "172.3.21.10"
3. Tested the behaviour with yb-managed cluster where load balancer is actually present.

### CODE REVIEW

File: yb-voyager/cmd/importData.go [hunk 1]
```diff
@@ -164,11 +160,7 @@ func getYBServers() []*tgtdb.Target {
 
 			// check if given host is one of the server in cluster
 			if loadBalancerUsed {
-				for _, ip := range potentialLBIps {
-					if ip.String() == host || ip.String() == public_ip {
-						loadBalancerUsed = false
-					}
-				}
+				tryMatchingWithTargetHost(host, public_ip)
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:163]: Rename the function as `isSeedHost(host, publicIP)`.
If the function returns true, set `loadBalancerUsed = false`.

File: yb-voyager/cmd/importData.go [hunk 2]
```diff
@@ -226,6 +218,47 @@ func testYbServers(targets []*tgtdb.Target) {
 	log.Infof("all target servers are accessible")
 }
 
+func tryMatchingWithTargetHost(private_ip string, public_ip string) {
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:221]: You can simplify using https://pkg.go.dev/golang.org/x/exp/slices#Contains

```
func isSeedHost(names ...string) bool {
        seedHostIPList, err := lookupIP(target.Host)
        // Handle err.
        
        var allIPs []string
        for _, name := range names {
                if name != "" {
                        allIPs = append(allIPs, lookupIP(name))
                }
        }
        for _, seedHostIP := range seedHostIPs {
                if slice.Contains(allIPs, seedHostIP) {
                        return true
                }
        }
        return false;
}

func lookupIP(name string) []string {
        var result []string

        ips, err = net.LookupIP(name)
        // Handle err.
        for _, ip := range ips {
                result = append(result, ip.String())
        }
        return result
}
```

Comment (sanyamsinghal) [reply yb-voyager/cmd/importData.go:221]: @amit-yb that's a nice way to code it. Will do it.
Initially, i thought to `slices.Contains()` directly but was getting an error due to slice elements being net.IP instead of string.

File: yb-voyager/cmd/importData.go [hunk 3]
```diff
@@ -164,11 +160,7 @@ func getYBServers() []*tgtdb.Target {
 
 			// check if given host is one of the server in cluster
 			if loadBalancerUsed {
-				for _, ip := range potentialLBIps {
-					if ip.String() == host || ip.String() == public_ip {
-						loadBalancerUsed = false
-					}
-				}
+				loadBalancerUsed = !isSeedTargetHost(host, public_ip)
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:163]: Nit: using simple if statement will better capture intent of the statement:
```
if loadBalancerUsed {
  if isSeedTargetHost(host, private_ip) {
    loadBalancerUsed = false
  }
}
```

File: yb-voyager/cmd/importData.go [hunk 4]
```diff
@@ -226,6 +218,24 @@ func testYbServers(targets []*tgtdb.Target) {
 	log.Infof("all target servers are accessible")
 }
 
+func isSeedTargetHost(names ...string) bool {
+	seedHostIPs := utils.LookupIP(target.Host)
```
Comment (amit-yb) [inline yb-voyager/cmd/importData.go:222]: Nit: Move this line after line 229.

**Review by amit-yb — APPROVED** [review]
LGTM: just a couple of minor nits.

**Review by amit-yb — APPROVED** [review]
